# Rozkład Choleskiego

Macierz *symetryczna* i *dodatnio określona* rozkłada się jednoznacznie na czynniki

$$A = LL^T$$

gdzie $L$ jest macierzą dolnie trójkątną postaci

$$L = \begin{bmatrix}l_{11} & 0 & ... & 0\\l_{21} & l_{22} & \ddots & \vdots\\\vdots & \ddots & \ddots & \vdots\\l_{n1} & &\ldots & l_{nn}\end{bmatrix}
$$

taką, że $l_{ii} > 0$ dla $i=1,2,3,\ldots,n$


Elementy macierzy $L$ powstałej w rozkładzie Choleskiego macierzy $A$ wyrażają się wzorami

$$l_{ss} =  \sqrt{a_{ss} - \sum_{j=1}^{s-1} l_{sj}^2}$$
$$l_{is} = \big{(} a_{is} - \sum_{j=1}^{s-1} l_{ij}l_{sj} \big{)} \big{/} l_{ss}$$

Rozwiązanie układu równań liniowych postaci $Ax = b$ przy wykorzystaniu rozkładu Choleskiego sprowadza się do rozwiązania układu dwóch równań liniowych o macierzach trójkątnych

$$ \begin{align}
Ly & = b \\
L^Tx & = y
\end{align}$$

W celu jego rozwiązania należy wykonać *postępowanie odwrotne Gaussa* dla macierzy dolnie trójkątnej i górnie trójkątnej

### Zadanie: Rozwiązać za pomocą rozkładu Choleskiego

$$ \begin{align}
A = \begin{bmatrix}1 & -2 & 3 & 1\\-2 & 5 & -8 & 1\\3 & -8 & 17 & -7\\1 & 1 & -7 & 18\end{bmatrix}
 b = \begin{bmatrix}1\\-1\\3\\-4\end{bmatrix}
\end{align}$$


- [x] sprawdzamy czy macierz A jest symetryczna
- [ ] sprawdzamy czy macierz A jest dodatnio określona -

czyli liczymy minory główne macierzy - wyznaczniki po kolei od lewego górnego rogu  1x1, 2x2, 3x3, 4x4 i sprawdzamy czy wszystkie są $> 0$

In [42]:
import numpy as np
import math
import scipy.linalg

A = np.array([[1,-2,3,1],[-2,5,-8,1],[3,-8,17,-7],[1,1,-7,18]])
b = np.array([1,-1,3,-4])

print(A)

[[ 1 -2  3  1]
 [-2  5 -8  1]
 [ 3 -8 17 -7]
 [ 1  1 -7 18]]


In [43]:
dodatnioOkreslona = True

for i in range(0,len(A)):
    # i = 0,1,2,3
    # A[from:to]
    # liczymy normalnie metoda laplace'a ale tutaj mozemy byc leniwymi chujami
    a = A[0:i+1,0:i+1]
    if(np.linalg.det(a) <= 0):
        dodatnioOkreslona = False
        break
        
if(dodatnioOkreslona):
    print("Macierz A jest dodatnio okreslona")
else:
    print("Macierz A nie jest dodatnio okreslona")

Macierz A jest dodatnio okreslona


Skoro tak, mozemy przystapic do układania macierzy L

In [44]:
L = np.zeros([len(A),len(A)]) # rozmiar taki jak A (4x4)

for s in range(0,len(L)):
    for i in range(0,len(L)):
        if(i != s):
            # wzor l_is
            sigma = 0
            for j in range(0,s):
                sigma += L[j][i]*L[j][s]                
            L[s][i] = A[s][i] - sigma
            if(L[s][s] != 0):
                L[s][i] = L[s][i]/L[s][s]
        else:
            # wzor l_ss
            sigma = 0
            for j in range(0,s):
                sigma += L[j][s]*L[j][s]
            L[s][s] = A[s][s] - sigma
            L[s][s] = math.sqrt(L[s][s])
L = L.transpose()
print(L)
print()
print(scipy.linalg.cholesky(A, lower=True)) # porownanie z rozkladem choleskiego z numpy

[[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [ 3. -2.  2.  0.]
 [ 1.  3. -2.  2.]]

[[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [ 3. -2.  2.  0.]
 [ 1.  3. -2.  2.]]


In [45]:
# liczymy y z ukladu rownan ( L * y = b)
y = np.linalg.solve(L,b)
print(y)

[ 1.  1.  1. -3.]


In [46]:
# a teraz majac y rozwiazujemy  (L^T * x = y)
x = np.linalg.solve(L.transpose(),y)
print(x)

[12.5  3.5 -1.  -1.5]


In [47]:
# a teraz za pomoca numpy sprawdzamy

res = np.linalg.solve(A,b)
print(A)
print("*")
print(b)
print("=")
print(res)

[[ 1 -2  3  1]
 [-2  5 -8  1]
 [ 3 -8 17 -7]
 [ 1  1 -7 18]]
*
[ 1 -1  3 -4]
=
[12.5  3.5 -1.  -1.5]
